# -*- coding: utf-8 -*-
"""Cleaned_Final_P1_Movement_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16y839yGsRfnrxM6pPWmfvkLmvFHzQQIX
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Komilo_proj/Datasets/MMA_Modified_Datasets/P1_Movement_Data.csv')

df.head()

# Check for missing values
print(df.isnull().sum())

df.columns = ['Time', 'Ax', 'Ay', 'Az', 'Gx', 'Gy', 'Gz', 'Movement']

missing_movement = df[df[['Movement']].isnull().values]
missing_movement
len(missing_movement)

df.Movement.value_counts(dropna=False)

if 'filename' in df.columns:
    cleaned_df = df.drop('filename', axis=1).dropna(subset=['Movement', 'Time'])
else:
    cleaned_df = df.dropna(subset=['Movement','Time'])

cleaned_df.Movement = cleaned_df.Movement.apply(str.upper)
cleaned_df.Movement.value_counts(dropna=False)

cleaned_df.Movement = cleaned_df.Movement.apply(str.upper)
cleaned_df.Movement.value_counts(dropna=False)

unique_Movement = df['Movement'].unique()
print("Unique Movements:", unique_Movement)

df['Movement'] = df['Movement'].str.strip()

df['Movement'] = df['Movement'].str.title()

df['Movement'] = df['Movement'].replace({
    'Drinking': 'Eating',    # Merge 'Drinking' into 'Eating'
    "Walking'": 'Walking',  # Fix incorrect label
    'walking': 'Walking',   # Ensure consistency with case
})

unique_Movement = df['Movement'].unique()
Movement_counts = df['Movement'].value_counts()
missing_values = df['Movement'].isna().sum()

print("Unique Movements:", unique_Movement)
print("\nMovement counts:")
print(Movement_counts)
print(f"\nTotal rows: {len(df)}")
print(f"Missing values in Movement column: {missing_values}")

import matplotlib.pyplot as plt

Movement_counts.plot(kind='bar', title='Distribution of Statuses', color='skyblue')
plt.xlabel('Movement')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

missing_time = cleaned_df[cleaned_df['Time'].isnull().values]
missing_time
len(missing_time)

cleaned_df.describe(include='all')

print(df.columns)

print(df.head())

print(df.info())

print(df.describe())

print(df)

df.to_csv("/content/drive/MyDrive/Komilo_proj/Data_Preparation/My_Work/Cleaned_Final_P1_Movement_Data.csv", index=False)